#!/usr/bin/env bash
# Bash function to display information about a subdomain
get_subdomain_info() {
    if [ "$#" -eq 1 ]
    then
    subdomains=('www' 'lb-01' 'web-01' 'web-02')
    for subdomain in "${subdomains[@]}"
    do
        RECORD_TYPE=$(dig $subdomain.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
        TARGET=$(dig $subdomain.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
        echo "The subdomain $subdomain is a $RECORD_TYPE record and points to $TARGET"
    done
    elif [ "$#" -eq 2 ]
    then
        RECORD_TYPE=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
        TARGET=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
        echo "The subdomain $2 is a $RECORD_TYPE record and points to $TARGET"
    fi
}
get_subdomain_info $1 $2