#!/usr/bin/env bash
# Configures new ubuntu machine by installing with 404
sudo apt update
sudo apt install -y nginx
sudo echo "Hello World" > /var/www/html/index.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;

    error_page 404 /404.html;
    location /404.html {
        try_files $uri $uri/ =404;
    }
}
" > /etc/nginx/sites-enabled/default
sudo service nginx restart