#!/usr/bin/env bash
# install load balancer on lb-01 server

sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*

haproxyconfig="frontend web-frontend
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
   balance roundrobin
   server 223286-web-01 54.237.78.187:80 check
   server 223286-web-02 54.234.4.8:80 check"

sudo chmod go+w /etc/haproxy/haproxy.cfg
echo "$haproxyconfig" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo chmod go+w /etc/default/haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null
sudo service haproxy restart
