#!/usr/bin/env bash
# modify default nginx server block configuration
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed -i 's/listen 80 default_server:/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
