#!/usr/bin/env bash
# displays the PID, along with the process name, of processes whose name contain the word bash
process_dirs=(/proc/[0-9]*)
for dir in "${process_dirs[@]}"; do
    process_name=$(awk -F' ' '/Name/ {print $2}' "$dir/status")
    if [[ $process_name == *"bash"* ]]; then
        pid=$(awk -F' ' '/Pid/ {print $2}' "$dir/status")
    echo "$pid $process_name"
    fi
done
