#!/usr/bin/env bash
# stops 4-to_infinity_and_beyond process.
4_pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$pid" ] && ps -p "$pid" >/dev/null; then
    kill -SIGINT "$pid"
    echo "Process with PID $pid has been stopped."
else
    echo "4-to_infinity_and_beyond process not found or already stopped."
fi
