#!/usr/bin/env bash
# Kills process 7 
pid=$(pgrep -f "7-highlander")
if [ -z "$pid" ]; then
    echo "Process '7-highlander' is not running"
else
    kill "$pid"
    echo "process '7-highlander' with PID $pid terminated"
fi
