#!/usr/bin/env bash
# Displays the time for 12hours and 59 minutes
hours=0
while [ $hours -le 12 ]
do
    minutes=1
    while [ $minutes -le 59 ]
    do
        printf "%02d:%02d\n" $hours $minutes
        ((minutes++))
    done
    ((hours++))
done | head -n 70
