#!/usr/bin/env bash
ifconfig_output=$(ifconfig)
ipv4_addresses=$(echo "$ifconfig_output" | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{print $2}')
echo "Active IPv4 IPs:"
echo "$ipv4_addresses"
