#!/usr/bin/env bash
#runs whoami to passed argument
if [ $# -eq 1 ]; then
    username="$1"

    if sudo -u "$username" whoami > /dev/null 2>&1; then
        result=$(sudo -u "$username" whoami)
        echo "$result"
    else
        echo "$username doesnt exist"
    fi
else
    echo "Please provide exactly one username as argument"
fi
