#!/bin/bash
#configurs nginx to run as nginx not root user
# Stop the Nginx service
service nginx stop

# Update the Nginx configuration to run as the nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Listen on all active IPs on port 8080
sed -i 's/listen 80;/listen *:8080;/' /etc/nginx/sites-available/default

# Restart Nginx
service nginx start

# Check if Nginx is running as the nginx user
if [[ "$(pgrep -ef | grep 'nginx: master' | grep -c 'nginx')" -eq 1 ]]; then
    echo "Nginx is now running as the nginx user."
else
    echo "Failed to configure Nginx to run as the nginx user."
fi

exit 0
