#!/bin/bash
#configurs nginx to run as nginx not root user
sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

sudo sed -i 's/user root;/user nginx;/g' /etc/nginx/nginx.conf

sudo service nginx restart
